require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe ProcessTypesController do

  # This should return the minimal set of attributes required to create a valid
  # ProcessType. As you add validations to ProcessType, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "string" => "" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # ProcessTypesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all process as @process" do
      process = ProcessType.create! valid_attributes
      get :index, {}, valid_session
      assigns(:process).should eq([process])
    end
  end

  describe "GET show" do
    it "assigns the requested process as @process" do
      process = ProcessType.create! valid_attributes
      get :show, {:id => process.to_param}, valid_session
      assigns(:process).should eq(process)
    end
  end

  describe "GET new" do
    it "assigns a new process as @process" do
      get :new, {}, valid_session
      assigns(:process).should be_a_new(ProcessType)
    end
  end

  describe "GET edit" do
    it "assigns the requested process as @process" do
      process = ProcessType.create! valid_attributes
      get :edit, {:id => process.to_param}, valid_session
      assigns(:process).should eq(process)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new ProcessType" do
        expect {
          post :create, {:process => valid_attributes}, valid_session
        }.to change(ProcessType, :count).by(1)
      end

      it "assigns a newly created process as @process" do
        post :create, {:process => valid_attributes}, valid_session
        assigns(:process).should be_a(ProcessType)
        assigns(:process).should be_persisted
      end

      it "redirects to the created process" do
        post :create, {:process => valid_attributes}, valid_session
        response.should redirect_to(ProcessType.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved process as @process" do
        # Trigger the behavior that occurs when invalid params are submitted
        ProcessType.any_instance.stub(:save).and_return(false)
        post :create, {:process => { "string" => "invalid value" }}, valid_session
        assigns(:process).should be_a_new(ProcessType)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        ProcessType.any_instance.stub(:save).and_return(false)
        post :create, {:process => { "string" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested process" do
        process = ProcessType.create! valid_attributes
        # Assuming there are no other process in the database, this
        # specifies that the ProcessType created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        ProcessType.any_instance.should_receive(:update).with({ "string" => "" })
        put :update, {:id => process.to_param, :process => { "string" => "" }}, valid_session
      end

      it "assigns the requested process as @process" do
        process = ProcessType.create! valid_attributes
        put :update, {:id => process.to_param, :process => valid_attributes}, valid_session
        assigns(:process).should eq(process)
      end

      it "redirects to the process" do
        process = ProcessType.create! valid_attributes
        put :update, {:id => process.to_param, :process => valid_attributes}, valid_session
        response.should redirect_to(process)
      end
    end

    describe "with invalid params" do
      it "assigns the process as @process" do
        process = ProcessType.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ProcessType.any_instance.stub(:save).and_return(false)
        put :update, {:id => process.to_param, :process => { "string" => "invalid value" }}, valid_session
        assigns(:process).should eq(process)
      end

      it "re-renders the 'edit' template" do
        process = ProcessType.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ProcessType.any_instance.stub(:save).and_return(false)
        put :update, {:id => process.to_param, :process => { "string" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested process" do
      process = ProcessType.create! valid_attributes
      expect {
        delete :destroy, {:id => process.to_param}, valid_session
      }.to change(ProcessType, :count).by(-1)
    end

    it "redirects to the process list" do
      process = ProcessType.create! valid_attributes
      delete :destroy, {:id => process.to_param}, valid_session
      response.should redirect_to(process_url)
    end
  end

end
