require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe SistemConfigurationsController do

  # This should return the minimal set of attributes required to create a valid
  # SistemConfiguration. As you add validations to SistemConfiguration, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "notification_period" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # SistemConfigurationsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all sistem_configurations as @sistem_configurations" do
      sistem_configuration = SistemConfiguration.create! valid_attributes
      get :index, {}, valid_session
      assigns(:sistem_configurations).should eq([sistem_configuration])
    end
  end

  describe "GET show" do
    it "assigns the requested sistem_configuration as @sistem_configuration" do
      sistem_configuration = SistemConfiguration.create! valid_attributes
      get :show, {:id => sistem_configuration.to_param}, valid_session
      assigns(:sistem_configuration).should eq(sistem_configuration)
    end
  end

  describe "GET new" do
    it "assigns a new sistem_configuration as @sistem_configuration" do
      get :new, {}, valid_session
      assigns(:sistem_configuration).should be_a_new(SistemConfiguration)
    end
  end

  describe "GET edit" do
    it "assigns the requested sistem_configuration as @sistem_configuration" do
      sistem_configuration = SistemConfiguration.create! valid_attributes
      get :edit, {:id => sistem_configuration.to_param}, valid_session
      assigns(:sistem_configuration).should eq(sistem_configuration)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new SistemConfiguration" do
        expect {
          post :create, {:sistem_configuration => valid_attributes}, valid_session
        }.to change(SistemConfiguration, :count).by(1)
      end

      it "assigns a newly created sistem_configuration as @sistem_configuration" do
        post :create, {:sistem_configuration => valid_attributes}, valid_session
        assigns(:sistem_configuration).should be_a(SistemConfiguration)
        assigns(:sistem_configuration).should be_persisted
      end

      it "redirects to the created sistem_configuration" do
        post :create, {:sistem_configuration => valid_attributes}, valid_session
        response.should redirect_to(SistemConfiguration.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved sistem_configuration as @sistem_configuration" do
        # Trigger the behavior that occurs when invalid params are submitted
        SistemConfiguration.any_instance.stub(:save).and_return(false)
        post :create, {:sistem_configuration => { "notification_period" => "invalid value" }}, valid_session
        assigns(:sistem_configuration).should be_a_new(SistemConfiguration)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        SistemConfiguration.any_instance.stub(:save).and_return(false)
        post :create, {:sistem_configuration => { "notification_period" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested sistem_configuration" do
        sistem_configuration = SistemConfiguration.create! valid_attributes
        # Assuming there are no other sistem_configurations in the database, this
        # specifies that the SistemConfiguration created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        SistemConfiguration.any_instance.should_receive(:update).with({ "notification_period" => "MyString" })
        put :update, {:id => sistem_configuration.to_param, :sistem_configuration => { "notification_period" => "MyString" }}, valid_session
      end

      it "assigns the requested sistem_configuration as @sistem_configuration" do
        sistem_configuration = SistemConfiguration.create! valid_attributes
        put :update, {:id => sistem_configuration.to_param, :sistem_configuration => valid_attributes}, valid_session
        assigns(:sistem_configuration).should eq(sistem_configuration)
      end

      it "redirects to the sistem_configuration" do
        sistem_configuration = SistemConfiguration.create! valid_attributes
        put :update, {:id => sistem_configuration.to_param, :sistem_configuration => valid_attributes}, valid_session
        response.should redirect_to(sistem_configuration)
      end
    end

    describe "with invalid params" do
      it "assigns the sistem_configuration as @sistem_configuration" do
        sistem_configuration = SistemConfiguration.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        SistemConfiguration.any_instance.stub(:save).and_return(false)
        put :update, {:id => sistem_configuration.to_param, :sistem_configuration => { "notification_period" => "invalid value" }}, valid_session
        assigns(:sistem_configuration).should eq(sistem_configuration)
      end

      it "re-renders the 'edit' template" do
        sistem_configuration = SistemConfiguration.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        SistemConfiguration.any_instance.stub(:save).and_return(false)
        put :update, {:id => sistem_configuration.to_param, :sistem_configuration => { "notification_period" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested sistem_configuration" do
      sistem_configuration = SistemConfiguration.create! valid_attributes
      expect {
        delete :destroy, {:id => sistem_configuration.to_param}, valid_session
      }.to change(SistemConfiguration, :count).by(-1)
    end

    it "redirects to the sistem_configurations list" do
      sistem_configuration = SistemConfiguration.create! valid_attributes
      delete :destroy, {:id => sistem_configuration.to_param}, valid_session
      response.should redirect_to(sistem_configurations_url)
    end
  end

end
